const AppConstants = {
  FETCHING_OPTIONS: 'FETCHING_OPTIONS',
  RECEIVED_OPTIONS: 'RECEIVED_OPTIONS',
  FETCHING_KEYBOARD_SHORTCUTS: 'FETCHING_KEYBOARD_SHORTCUTS',
  RECEIVED_KEYBOARD_SHORTCUTS: 'RECEIVED_KEYBOARD_SHORTCUTS',
};

export default AppConstants;
